# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
#src     = Glob('*.c') + Glob('*.S')
if GetDepend('RT_USING_LWIP202'):
    src = ['airkiss_lan_raw.c']
else:
    src = ['airkiss_lan.c']

libs    = ['airkiss']
libpath = [cwd]
CPPPATH = [cwd]

group = DefineGroup('airkiss', src, depend = ['RT_USING_AIRKISS'], CPPPATH = CPPPATH, LIBPATH = libpath)

Return('group')
