from building import *

cwd = GetCurrentDir()

src = Glob('*.c')
list = os.listdir(cwd)

objs = []
libs  = ['Cchip_gcc']
libpath  = [cwd]
path = [cwd]
group = DefineGroup('Cchip', src, depend = [''], LIBS = libs, LIBPATH = libpath, CPPPATH = path)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group
Return('objs')
