# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.S')
libs    = ['airkiss']
libpath = [cwd]
CPPPATH = [cwd]

group = DefineGroup('i2c_sample', src, depend = ['RT_USING_AIRKISS'], CPPPATH = CPPPATH, LIBS = libs, LIBPATH = libpath)

Return('group')
