# RT-Thread building script for component
from building import *

cwd = GetCurrentDir()

src = ['voice_config.c']
CPPPATH = [cwd, cwd + '/include']
objs = []
libs = ['voice_config_arm968_gcc']
libpath = [cwd + '/libs']

group = DefineGroup('voice_config', src, depend = [''], CPPPATH = CPPPATH, LIBS = libs, LIBPATH = libpath)

objs = objs + group
Return('objs')
